package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private final JoinPredicate p;
    private OpIterator child1;
    private OpIterator child2;
    private TupleIterator joinIterator;
    private TupleDesc td;
    private OpIterator child11;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        this.child1 = child1;
        this.child2 = child2;
        this.p = p;
        this.joinIterator = null;
        this.td = TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public JoinPredicate getJoinPredicate() {
        return p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        return child1.getTupleDesc().toString();
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        return child2.getTupleDesc().toString();
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        return td;
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        child1.open();
        child2.open();
        super.open();
        joinIterator = createJoinIterator();
        joinIterator.open();
    }

    private TupleIterator createJoinIterator() throws DbException, TransactionAbortedException {
        List<Tuple> tuples = new ArrayList<>();
        while (child1.hasNext()) {
            Tuple t1 = child1.next();
            // loop around child2
            while (child2.hasNext()) {
                Tuple t2 = child2.next();
                // if match, create a combined tuple and fill it with the values
                // from both tuples
                if (!p.filter(t1, t2)) {
                    continue;
                }

                int td1n = t1.getTupleDesc().numFields();
                int td2n = t2.getTupleDesc().numFields();
                // set fields in combined tuple
                Tuple t = new Tuple(td);
                for (int i = 0; i < td1n; i++)
                    t.setField(i, t1.getField(i));
                for (int i = 0; i < td2n; i++)
                    t.setField(td1n + i, t2.getField(i));
                tuples.add(t);
            }
            child2.rewind();
        }

        return new TupleIterator(td, tuples);
    }

    public void close() {
        child1.close();
        child2.close();
        super.close();
        joinIterator.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        joinIterator.rewind();
    }

    public boolean hasNext() {
        return joinIterator.hasNext();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        if (joinIterator.hasNext()) {
            return joinIterator.next();
        }
        return null;
    }

    @Override
    public OpIterator[] getChildren() {
        return new OpIterator[]{this.child1, this.child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        this.child1 = children[0];
        this.child2 = children[1];
    }

}
